# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev
stages:
- stage: 
  pool:
    vmImage: windows-latest
  jobs:
  - job: backend_build
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.sln'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.sln'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'backend'
        publishLocation: 'Container'
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'backend'
        downloadPath: '$(System.ArtifactsDirectory)'
  - job: frontend_build
    pool:
     VmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '14.x'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'npm'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'npm'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)dist\packages\account'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'frontend'
        downloadPath: '$(System.ArtifactsDirectory)'